name: my_3containers
services:
  web:
    build: ./web
    container_name: my-web
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - appBackend
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: my-api
    ports:
      #公開ポートはreact等と被らないよう3001などとする。外部:内部
      - 3001:3000
    restart: unless-stopped
    networks:
      - appBackend
    depends_on:
      - db
  db:
    build: ./db
    container_name: my-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - appBackend

networks:
  appBackend:
    driver: bridge